<?php

namespace Dasundev\PayHere\Enums;

enum MessageType: string
{
    case AUTHORIZATION_SUCCESS = 'AUTHORIZATION SUCCESS';
    case AUTHORIZATION_FAILED = 'AUTHORIZATION FAILED';
    case RECURRING_INSTALLMENT_SUCCESS = 'RECURRING INSTALLMENT SUCCESS';
    case RECURRING_INSTALLMENT_FAILED = 'RECURRING INSTALLMENT FAILED';
    case RECURRING_COMPLETE = 'RECURRING COMPLETE';
    case RECURRING_STOPPED = 'RECURRING STOPPED';
}
