name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        laravel: [10, 11]

    name: Test PHP ${{ matrix.php }} with Laravel ${{ matrix.laravel }}
    
    env:
      SMEE_URL: https://smee.io/9WLG7veUpcwYCEb-${{ strategy.job-index }}

    steps:        
      - uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --${{ matrix.stability }}
          
      - name: Install Smee Client
        run: npm install -g smee-client

      - name: Start Chrome Driver
        run: vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel Server
        run: php vendor/bin/testbench serve --no-reload &

      - name: Start PayHere Webhook Listener
        run: smee -t http://localhost:8001/payhere/webhook -u ${{ env.SMEE_URL }} &

      - name: Run Tests
        run: composer run test
        env:
          PAYHERE_MERCHANT_ID: ${{ secrets.PAYHERE_MERCHANT_ID }}
          PAYHERE_MERCHANT_SECRET: ${{ secrets.PAYHERE_MERCHANT_SECRET }}
          PAYHERE_APP_ID: ${{ secrets.PAYHERE_APP_ID }}
          PAYHERE_APP_SECRET: ${{ secrets.PAYHERE_APP_SECRET }}
          PAYHERE_NOTIFY_URL: ${{ env.SMEE_URL }}
          PAYHERE_SANDBOX: true

      - name: Upload Failed Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots/*