name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        laravel: [10, 11]

    name: Test PHP ${{ matrix.php }} with Laravel ${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress --${{ matrix.stability }}

      - name: Start Chrome Driver
        run: vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel Server
        run: php vendor/bin/testbench serve --no-reload &

      - name: Install Hookdeck CLI
        run: |
          VERSION=0.10.1
          FILE_NAME=hookdeck_${VERSION}_linux_amd64.tar.gz
          URL=https://github.com/hookdeck/hookdeck-cli/releases/download/v${VERSION}/${FILE_NAME}
          
          curl -LO ${URL} || { echo "Failed to download ${FILE_NAME}"; exit 1; }
          
          tar -xvf ${FILE_NAME} || { echo "Failed to extract ${FILE_NAME}"; exit 1; }
          
          sudo mv hookdeck /usr/local/bin/
          
          rm ${FILE_NAME}

      - name: Configure Hookdeck Workspace
        run: hookdeck ci --api-key ${{ secrets.HOOKDECK_API_KEY }}

      - name: Listen to PayHere Webhook
        run: hookdeck listen 8000 payhere &

      - name: Run Tests
        run: composer run test
        env:
          PAYHERE_MERCHANT_ID: ${{ secrets.PAYHERE_MERCHANT_ID }}
          PAYHERE_MERCHANT_SECRET: ${{ secrets.PAYHERE_MERCHANT_SECRET }}
          PAYHERE_APP_ID: ${{ secrets.PAYHERE_APP_ID }}
          PAYHERE_APP_SECRET: ${{ secrets.PAYHERE_APP_SECRET }}
          PAYHERE_NOTIFY_URL: ${{ secrets.PAYHERE_NOTIFY_URL }}

      - name: Upload Failed Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots/*